#!/usr/bin/env python3
"""The sabre benchmarking suite.

Where `run.py` answers "is sabre faster than titiler on these requests", this
answers "what can sabre carry, and did that change since last week". The
difference is the load model: run.py is closed-loop and reports one point per
concurrency level, which is a comparison; this adds an open-loop rate sweep
that finds the point where the server stops keeping up, which is a capacity.

Load is generated by bench-client (a Rust binary) rather than in Python. The
orchestration stays here because it needs the tile arithmetic, docker, and the
nginx access log, none of which belong in a load generator.

    cargo build --release -p sabre-bench-client
    python3 bench/suite.py --out bench/out/suite

Results carry the git branch and commit so successive runs can be compared,
and can be published to a Space with bench/publish.py.
"""

from __future__ import annotations

import argparse
import base64
import binascii
import hashlib
import importlib.util
import json
import os
import platform
import random
import subprocess
import sys
import threading
import time

HERE = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.dirname(HERE)


def _load_run_module():
    """Reuse run.py rather than reimplement tile maths and log parsing.

    It is a script, not a package, so it is loaded by path. Registering it in
    sys.modules before execution is required: its dataclasses look themselves
    up by __module__ while the class body is being processed.
    """
    spec = importlib.util.spec_from_file_location("benchrun", os.path.join(HERE, "run.py"))
    mod = importlib.util.module_from_spec(spec)
    sys.modules["benchrun"] = mod
    spec.loader.exec_module(mod)
    return mod


R = _load_run_module()


# ── Plans ─────────────────────────────────────────────────────────────────────

def target_of(req) -> dict:
    """run.py's Req -> a bench-client target."""
    return {
        "method": req.method,
        "path": req.path,
        "body": req.body.decode() if isinstance(req.body, bytes) else req.body,
        "headers": dict(req.headers or {}),
    }


def accept_for(server) -> list:
    # sabre answers a point on nodata with 400 and a fixed body, where titiler
    # returns 200 and a null value. Both are answers, and counting sabre's as a
    # failure would make its error column meaningless on nodata-heavy data.
    return [200, 400] if server.name == "sabre" else [200]


def plan_of(name: str, server, reqs: list, mode: dict, *, duration: float, warmup: float) -> dict:
    return {
        "name": f"{server.name} {name}",
        "base": server.base,
        "mode": mode,
        "duration_s": duration,
        "warmup_s": warmup,
        "accept_statuses": accept_for(server),
        "targets": [target_of(r) for r in reqs],
    }


# ── Driving bench-client ──────────────────────────────────────────────────────

class Client:
    """Runs bench-client, either here or on another machine.

    With `ssh` set, the generator runs on a second droplet and only the plan
    (on stdin) and the result (on stdout) cross the wire. The orchestrator
    stays on the server box because it needs docker, the compose file and the
    nginx access log, none of which exist on the generator.
    """

    def __init__(self, binary: str, quiet: bool = True, ssh: str | None = None) -> None:
        self.binary = binary
        self.quiet = quiet
        self.ssh = ssh

    @property
    def where(self) -> str:
        return f"{self.ssh}:{self.binary}" if self.ssh else "local"

    def check(self) -> None:
        """Fail now, with a usable message, rather than once per phase."""
        if not self.ssh:
            if not os.path.exists(self.binary):
                sys.exit(f"bench-client not found at {self.binary}\n"
                         f"Build it first:  cargo build --release -p sabre-bench-client")
            return
        probe = subprocess.run(
            ["ssh", "-o", "BatchMode=yes", "-o", "ConnectTimeout=10", self.ssh,
             f"test -x {self.binary} && {self.binary} --help >/dev/null"],
            capture_output=True, timeout=60,
        )
        if probe.returncode != 0:
            sys.exit(f"cannot run {self.binary} on {self.ssh}: "
                     f"{probe.stderr.decode().strip() or 'exit ' + str(probe.returncode)}\n"
                     f"Build it there first:  ssh {self.ssh} 'cd /root/sabre && bash bench/build-client.sh'")

    def run(self, plan: dict, *, rate=None, duration=None) -> dict | None:
        argv = [self.binary]
        if rate is not None:
            argv += ["--rate", repr(float(rate))]
        if duration is not None:
            argv += ["--duration", repr(float(duration))]
        if self.quiet:
            argv.append("--quiet")
        if self.ssh:
            # The plan still arrives on stdin; ssh just carries it.
            argv = ["ssh", "-o", "BatchMode=yes", "-o", "ConnectTimeout=10", self.ssh, " ".join(argv)]
        try:
            out = subprocess.run(argv, input=json.dumps(plan).encode(),
                                 capture_output=True, timeout=1800)
        except (OSError, subprocess.TimeoutExpired) as e:
            print(f"  bench-client failed: {e}", file=sys.stderr)
            return None
        if out.returncode != 0:
            print(f"  bench-client exited {out.returncode}: {out.stderr.decode()[:400]}", file=sys.stderr)
            return None
        if not self.quiet and out.stderr:
            sys.stderr.write(out.stderr.decode())
        try:
            return json.loads(out.stdout)
        except json.JSONDecodeError:
            print("  bench-client produced no parseable result", file=sys.stderr)
            return None


# ── The knee ──────────────────────────────────────────────────────────────────

def tracking(summary, tolerance: float) -> bool:
    """Is the server still keeping up with the offered rate?

    Achieved rate, not latency, is the test. Latency rising is expected as
    queues fill; what marks saturation is requests arriving faster than they
    leave. A generator that fell behind its own schedule cannot answer the
    question either way, so that counts as not tracking.
    """
    if summary is None or summary.get("client_saturated") or summary.get("overloaded"):
        return False
    offered = summary.get("offered_rps") or 0.0
    return offered > 0 and summary["achieved_rps"] >= offered * tolerance


def find_knee(client: Client, plan: dict, *, seed_rps: float, probe_s: float,
              confirm_s: float, tolerance: float = 0.95, refine: int = 3,
              max_probes: int = 8) -> dict:
    """Ramp until the server stops tracking, then bisect.

    Seeded from the closed-loop throughput already measured rather than from a
    fixed number, so the ramp starts near the answer instead of walking up from
    nothing: a server that does 3,000 req/s should not be probed at 100.
    """
    probes = []
    rate = max(seed_rps * 0.5, 10.0)
    good = None
    bad = None

    for _ in range(max_probes):
        s = client.run(plan, rate=rate, duration=probe_s)
        probes.append({"rate": rate, "summary": s})
        if tracking(s, tolerance):
            good = rate
            rate *= 2.0
        else:
            bad = rate
            break

    if good is None:
        return {"knee_rps": None, "probes": probes,
                "note": "did not track even the lowest rate probed; seed was too high"}
    if bad is None:
        return {"knee_rps": good, "probes": probes,
                "note": f"still tracking at {good:g} req/s after {max_probes} probes; the knee is above this"}

    for _ in range(refine):
        mid = (good + bad) / 2.0
        s = client.run(plan, rate=mid, duration=probe_s)
        probes.append({"rate": mid, "summary": s})
        if tracking(s, tolerance):
            good = mid
        else:
            bad = mid

    confirm = client.run(plan, rate=good, duration=confirm_s)
    probes.append({"rate": good, "summary": confirm, "confirm": True})
    return {
        "knee_rps": good,
        "first_failing_rps": bad,
        "confirmed": tracking(confirm, tolerance),
        "confirm_summary": confirm,
        "probes": probes,
    }


def measure_floor(client: Client, server, *, duration: float) -> dict | None:
    """The cheapest round trip the setup can do, against /health.

    With the generator on another droplet every measurement carries the network
    between them. That is a rounding error on a 26 ms polygon and it is the
    entire result for a 0.3 ms /info, so the floor is measured rather than
    assumed, and any phase whose p50 comes within 3x of it is marked in the
    report as describing the path more than the server.
    """
    plan = {
        "name": f"{server.name} floor",
        "base": server.base,
        "mode": {"closed": {"concurrency": 1}},
        "duration_s": duration,
        "warmup_s": 1.0,
        "accept_statuses": [200],
        "targets": [{"method": "GET", "path": server.health_path, "body": None, "headers": {}}],
    }
    s = client.run(plan)
    if not s or not s["ok"]:
        return None
    return {"p50_ms": s["service_ms"]["p50"], "p99_ms": s["service_ms"]["p99"], "samples": s["ok"]}


# ── Provenance ────────────────────────────────────────────────────────────────

# Set by remote-bench.sh to base64-encoded JSON from `suite.py --print-git`,
# run on the operator's machine. The benchmark box gets the working tree by
# rsync with `.git` excluded, so git there reports nothing at all -- and
# "nothing" must not be mistaken for "clean".
GIT_ENV = "SABRE_BENCH_GIT_B64"


def git_meta() -> dict:
    """Provenance for the code under test.

    Every field can legitimately be None, so `available` carries whether git
    answered at all. Without it, a box with no `.git` produced
    `{"commit": None, "dirty": False}` -- which reads as a clean run of an
    unknown commit, and publish.py accepted it.
    """
    passed = os.environ.get(GIT_ENV)
    if passed:
        try:
            meta = json.loads(base64.b64decode(passed))
        except (ValueError, binascii.Error) as exc:
            sys.exit(f"{GIT_ENV} is set but is not base64-encoded JSON: {exc}")
        meta["source"] = "orchestrator"
        return meta

    def g(*args, default=None):
        try:
            out = subprocess.run(["git", "-C", REPO, *args], capture_output=True, text=True, timeout=15)
        except (OSError, subprocess.TimeoutExpired):
            return default
        return out.stdout.strip() if out.returncode == 0 else default

    commit = g("rev-parse", "HEAD")
    if commit is None:
        # No repository here. Say so, rather than reporting a clean tree at an
        # unknown commit.
        return {
            "available": False,
            "reason": f"git could not read {REPO}; run suite.py where the repository is, "
                      f"or pass {GIT_ENV} from a machine that has it",
            "branch": None, "commit": None, "short": None,
            "describe": None, "subject": None, "committed": None,
            "dirty": None, "dirty_files": None,
        }

    dirty = g("status", "--porcelain", default="") or ""
    return {
        "available": True,
        "branch": g("rev-parse", "--abbrev-ref", "HEAD"),
        "commit": commit,
        # Fixed width: `--short` returns the shortest unambiguous prefix, which
        # grows as the repo does, so it would not match the image tag.
        "short": commit[:7],
        "describe": g("describe", "--tags", "--always", "--dirty"),
        "subject": g("log", "-1", "--format=%s"),
        "committed": g("log", "-1", "--format=%cI"),
        # A dirty tree means the commit does not describe what was measured.
        # Recorded rather than refused, but it should disqualify a result from
        # being treated as *the* number for that commit.
        "dirty": bool(dirty),
        "dirty_files": len(dirty.splitlines()) if dirty else 0,
    }


# ── Resources ─────────────────────────────────────────────────────────────────

class Resources:
    """Samples the server's memory while a phase runs.

    Throughput headroom says nothing about footprint. A box with 100x the
    capacity it needs can still be killed by a cache that grows with the
    variety of what is asked for rather than with the rate, or by per-request
    buffers that scale with concurrency. Neither shows up in a latency figure,
    and both show up here.

    `spec` is `pid:<n>` or `docker:<service>`. Sampling is best-effort: a
    backend that cannot answer reports nothing rather than zero, because a
    flat zero line reads as "no growth" when it means "not looked".
    """

    INTERVAL_S = 0.25

    def __init__(self, spec: str, compose_file: str = "") -> None:
        self.spec = spec or ""
        self.compose_file = compose_file
        self.kind, _, self.target = self.spec.partition(":")
        self._stop = threading.Event()
        self._samples: list[float] = []
        self._thread: threading.Thread | None = None
        self.available = bool(self.target) and self.probe() is not None

    def probe(self) -> float | None:
        """Resident set size in MB, or None if it cannot be read."""
        try:
            if self.kind == "pid":
                out = subprocess.run(["ps", "-o", "rss=", "-p", self.target],
                                     capture_output=True, text=True, timeout=5)
                kb = out.stdout.strip()
                return int(kb) / 1024 if kb else None
            if self.kind == "docker":
                cmd = ["docker"]
                if self.compose_file:
                    cmd += ["compose", "-f", self.compose_file, "ps", "-q", self.target]
                    cid = subprocess.run(cmd, capture_output=True, text=True, timeout=10).stdout.strip()
                    if not cid:
                        return None
                else:
                    cid = self.target
                out = subprocess.run(
                    ["docker", "stats", "--no-stream", "--format", "{{.MemUsage}}", cid],
                    capture_output=True, text=True, timeout=15)
                # "123.4MiB / 2GiB"
                used = out.stdout.split("/")[0].strip()
                for suffix, mult in (("GiB", 1024), ("MiB", 1), ("KiB", 1 / 1024), ("B", 1 / 1048576)):
                    if used.endswith(suffix):
                        return float(used[: -len(suffix)]) * mult
                return None
        except (OSError, ValueError, subprocess.SubprocessError):
            return None
        return None

    def start(self) -> None:
        if not self.available:
            return
        self._samples = []
        self._stop.clear()

        def run() -> None:
            while not self._stop.wait(self.INTERVAL_S):
                mb = self.probe()
                if mb is not None:
                    self._samples.append(mb)

        self._thread = threading.Thread(target=run, daemon=True)
        self._thread.start()

    def stop(self) -> dict | None:
        if not self.available or self._thread is None:
            return None
        self._stop.set()
        self._thread.join(timeout=2)
        self._thread = None
        if not self._samples:
            return None
        s = sorted(self._samples)
        return {
            "rss_mb_start": round(self._samples[0], 1),
            "rss_mb_p50": round(s[len(s) // 2], 1),
            "rss_mb_peak": round(s[-1], 1),
            "rss_mb_end": round(self._samples[-1], 1),
            "samples": len(s),
        }


# ── Real workloads ────────────────────────────────────────────────────────────

def load_farms(blocks_dir: str, scenes_dir: str, want: str = "") -> list[dict]:
    """Block sets paired with the Sentinel-2 scene they sit on.

    Both halves are needed: blocks without imagery have nothing to read, and
    imagery without blocks is just another tile suite. A set missing either is
    skipped with a reason rather than silently dropped, because a quietly
    shorter run still produces a full-looking report.
    """
    index_path = os.path.join(blocks_dir, "index.json")
    manifest_path = os.path.join(scenes_dir, "manifest.json")
    if not os.path.exists(index_path):
        return []
    with open(index_path) as fh:
        sets = json.load(fh)["sets"]
    scenes = {}
    if os.path.exists(manifest_path):
        with open(manifest_path) as fh:
            scenes = json.load(fh).get("scenes") or {}

    wanted = {w.strip() for w in want.split(",") if w.strip()} if want else None
    farms = []
    for entry in sets:
        name = entry["name"]
        if wanted and name not in wanted:
            continue
        path = os.path.join(blocks_dir, entry["file"])
        if not os.path.exists(path):
            print(f"  note: {name} is in the index but {entry['file']} is missing; skipping")
            continue
        scene = scenes.get(name)
        if not scene:
            print(f"  note: {name} has no Sentinel-2 scene; run bench/fetch_scenes.py. Skipping.")
            continue
        missing = [k for k, a in scene.get("assets", {}).items()
                   if not os.path.exists(os.path.join(scenes_dir, a["file"]))]
        if missing:
            print(f"  note: {name}'s scene is missing {', '.join(missing)} on disk; skipping")
            continue
        with open(path) as fh:
            doc = json.load(fh)
        farms.append({
            "name": name,
            "shape": doc["shape"],
            "features": doc["features"],
            "scene": scene,
        })
    if wanted:
        found = {f["name"] for f in farms}
        for miss in sorted(wanted - found):
            print(f"  note: --farms asked for {miss}, which is not available")
    return farms


def scene_url(origin: str, server_name: str, scene: dict, asset: str) -> str | None:
    """Where a server reads one asset of a scene.

    The per-server prefix is what lets the origin log attribute range requests;
    nginx aliases both prefixes to the same directory, so there is one copy of
    the file behind two paths.
    """
    a = (scene.get("assets") or {}).get(asset)
    return f"{origin}/{server_name}/scenes/{a['file']}" if a else None


def host_meta() -> dict:
    info = {
        "platform": platform.platform(),
        "machine": platform.machine(),
        "cpu_count": os.cpu_count(),
    }
    # The CPU model matters more than the count: results from a shared vCPU and
    # a dedicated one are not comparable even at the same core count.
    try:
        if sys.platform == "darwin":
            info["cpu"] = subprocess.run(["sysctl", "-n", "machdep.cpu.brand_string"],
                                         capture_output=True, text=True, timeout=10).stdout.strip()
            mem = subprocess.run(["sysctl", "-n", "hw.memsize"],
                                 capture_output=True, text=True, timeout=10).stdout.strip()
            info["memory_gb"] = round(int(mem) / 2**30, 1) if mem.isdigit() else None
        else:
            with open("/proc/cpuinfo") as f:
                for line in f:
                    if line.startswith("model name"):
                        info["cpu"] = line.split(":", 1)[1].strip()
                        break
            with open("/proc/meminfo") as f:
                for line in f:
                    if line.startswith("MemTotal"):
                        info["memory_gb"] = round(int(line.split()[1]) / 2**20, 1)
                        break
    except (OSError, ValueError, subprocess.TimeoutExpired):
        pass
    return info


def dataset_meta(path: str) -> dict:
    """Fingerprint the raster, so two runs can be told apart when it changed."""
    if not path or not os.path.exists(path):
        return {"path": path, "present": False}
    h = hashlib.sha256()
    with open(path, "rb") as f:
        for chunk in iter(lambda: f.read(1 << 20), b""):
            h.update(chunk)
    return {"path": path, "present": True, "bytes": os.path.getsize(path), "sha256": h.hexdigest()}


# ── Report ────────────────────────────────────────────────────────────────────

def soak_rows(entries: list) -> str:
    """One row per server at a held rate: latency, bytes, and footprint."""
    rows = []
    for e in entries:
        s = e.get("summary")
        if s is None:
            rows.append([e["server"], "-", "-", "-", "-", "-", "-", "-"])
            continue
        served = s["ok"]
        kb = (s["bytes"] / served / 1024) if served else 0.0
        r = e.get("rss") or {}
        rows.append([
            e["server"],
            f"{s['achieved_rps']:.1f}",
            f"{s['service_ms']['p50']:.2f}",
            f"{s['service_ms']['p95']:.2f}",
            f"{s['service_ms']['p99']:.2f}",
            f"{kb:.1f}",
            f"{r['rss_mb_p50']:.0f}" if r else "n/a",
            f"{r['rss_mb_peak']:.0f}" if r else "n/a",
        ])
    return R.table(["server", "req/s", "p50 ms", "p95 ms", "p99 ms", "KB/req",
                    "rss p50", "rss peak"], rows)


def phase_rows(entries: list) -> str:
    """Where the server says its time went, per phase.

    `service p50` is what the client measured; the phases are what the server
    accounted for. The gap between them is the network, the accept, and
    anything outside the instrumented path -- and it is as worth reading as the
    phases, because a large one means time is going somewhere nothing is
    watching.
    """
    rows = []
    for e in entries:
        s = e.get("summary")
        if not s or not s.get("phases"):
            continue
        accounted = sum(p["ms"]["p50"] for p in s["phases"])
        service = s["service_ms"]["p50"]
        # Pre-formatted: R.table rounds floats to one decimal, which turns
        # every sub-millisecond phase into 0.0 and the whole table into a
        # column of zeroes.
        for p in s["phases"]:
            rows.append([e["server"], p["name"], f"{p['ms']['p50']:.3f}",
                         f"{p['ms']['p99']:.3f}", f"{p['share_pct']:.0f}%",
                         f"{p['samples']:,}"])
        rows.append([e["server"], "— accounted", f"{accounted:.3f}", "", "100%", ""])
        rows.append([e["server"], "— service p50", f"{service:.3f}", "",
                     f"{100 * accounted / service:.0f}% of it" if service > 0 else "", ""])
    if not rows:
        return ""
    return R.table(["server", "phase", "p50 ms", "p99 ms", "share", "n"], rows)


def closed_rows(entries: list, results: dict | None = None) -> str:
    rows = []
    for e in entries:
        s = e["summary"]
        if s is None:
            rows.append([e["server"], "-", "-", "-", "-", "-", "-", "-", "-", "-"])
            continue
        p50 = s["service_ms"]["p50"]
        rows.append([
            e["server"], s["ok"], s["errors"],
            round(p50, 2), round(s["service_ms"]["p95"], 2),
            round(s["service_ms"]["p99"], 2), round(s["service_ms"]["p999"], 2),
            round(s["achieved_rps"], 1), round(s["mb_per_s"], 1),
            "floor" if results and near_floor(results, e["server"], p50) else "",
        ])
    return R.table(["server", "ok", "err", "p50 ms", "p95 ms", "p99 ms", "p99.9 ms", "req/s", "MB/s", ""], rows)


def knee_rows(entries: list) -> str:
    rows = []
    for e in entries:
        k = e["knee"]
        c = k.get("confirm_summary") or {}
        rows.append([
            e["server"],
            R.fmt(k.get("knee_rps"), 0) if k.get("knee_rps") else "n/a",
            R.fmt(k.get("first_failing_rps"), 0) if k.get("first_failing_rps") else "-",
            round(c.get("service_ms", {}).get("p50", float("nan")), 2) if c else "-",
            round(c.get("service_ms", {}).get("p99", float("nan")), 2) if c else "-",
            len(k.get("probes", [])),
            "yes" if k.get("confirmed") else "no",
        ])
    return R.table(["server", "sustained req/s", "first failing", "p50 ms", "p99 ms", "probes", "confirmed"], rows)


def near_floor(results: dict, server: str, p50: float) -> bool:
    """Is this phase measuring the path rather than the server?

    Three times the floor is the line. Below it, most of what the number
    reports is the round trip that every request pays regardless of what the
    server does, and comparing two servers on it compares neither.
    """
    f = (results.get("floor") or {}).get(server)
    return bool(f and p50 is not None and p50 < f["p50_ms"] * 3)


def build_report(results: dict) -> str:
    g = results["git"]
    h = results["host"]
    out = [
        f"# sabre benchmark suite — {results['started']}",
        "",
        (f"`{g.get('branch')}` @ `{g.get('short')}` — {g.get('subject') or ''}"
         + ("  **(working tree dirty: this is not the number for this commit)**" if g.get("dirty") else "")
         if g.get("available") else
         "**Provenance unknown — this run is not attributable to a commit.**  \n"
         f"{g.get('reason') or 'git metadata was unavailable.'}"),
        "",
        f"Host: {h.get('cpu') or h.get('platform')}, {h.get('cpu_count')} cores, {h.get('memory_gb')} GB.",
    ]
    d = results.get("dataset") or {}
    if d.get("present"):
        out.append(f"Dataset: {d['path']}, {d['bytes'] / 1e6:.1f} MB, sha256 `{d['sha256'][:16]}…`.")

    for farm in results.get("farms") or []:
        sh = farm["shape"]
        sc = farm.get("scene") or {}
        out += ["",
                f"Farm `{farm['name']}`: {sh['blocks']} real blocks, "
                f"{sh['area_ha']['p50']} ha median ({sh['area_ha']['min']}–{sh['area_ha']['max']}), "
                f"{sh['vertices']['p50']} vertices median"
                + (f", {sh['holes']} interior rings" if sh.get("holes") else "")
                + f", over {sh['span_km'][0]}×{sh['span_km'][1]} km.",
                f"Imagery: `{sc.get('scene_id')}` "
                f"({(sc.get('datetime') or '')[:10]}, {sc.get('cloud_cover')}% cloud, "
                f"EPSG:{sc.get('epsg')}), copied byte-exact from sentinel-cogs."]
    if results.get("farms"):
        out += ["",
                "These are the requests production makes. They are small — a median block is a "
                "few hundred pixels against the synthetic polygon suite's 262,144 — and they are "
                "clustered, so a whole farm lands in a couple of the scene's 1024 px COG tiles "
                "rather than scattering across it. Both differences favour whichever server "
                "caches better, which the random-box suites above are built to defeat."]

    topo = results.get("topology") or {}
    if topo.get("generator") == "split":
        out += ["",
                f"Load generated from `{topo.get('generator_host')}`, a separate machine, so it does "
                "not compete with the servers for cores. Every figure therefore includes the network "
                "between them; the floor below is what that costs.",
                ""]
        if topo.get("loopback_suites"):
            out.append(f"Exceptions kept on a local generator, being faster than the network: "
                       f"`{'`, `'.join(topo['loopback_suites'])}`.")
    else:
        out += ["",
                "Load generated on the same box as the servers, so the two compete for cores. "
                "The fastest suites are limited by the generator rather than by the server.",
                ""]

    floor = results.get("floor") or {}
    if any(floor.values()):
        rows = [[k, f"{v['p50_ms']:.3f}", f"{v['p99_ms']:.3f}"]
                for k, v in sorted(floor.items()) if v]
        out += ["", "### Round-trip floor", "",
                "`GET /health` at concurrency 1 — the cheapest round trip this setup can do. "
                "A phase whose p50 is within 3x of it is marked *floor* below and describes "
                "the path more than the server.", "",
                R.table(["server", "p50 ms", "p99 ms"], rows), ""]
    out.append("")

    if results.get("knee"):
        out += ["## Sustained throughput", "",
                "Highest open-loop rate the server still kept up with — requests arrive on a",
                "fixed schedule, so this is capacity rather than a closed-loop data point.", ""]
        for phase in results["knee"]:
            out += [f"### {phase['suite']}", "", knee_rows(phase["entries"]), ""]

    if any(p["suite"].startswith("clip ") for p in (results.get("closed") or [])):
        out += ["",
                "In the `clip` phases the two servers are asked the same question — a 256×256 PNG "
                "of one field and nothing around it — by different routes. sabre attaches a cutline "
                "to an ordinary tile request; titiler has no cutline on `/cog/tiles`, so it uses "
                "`/cog/feature`, which frames the image on the field's own bounds rather than on "
                "the tile grid. Same output size and the same work; not the same framing.", ""]

    if results.get("cold"):
        rows = []
        for phase in results["cold"]:
            for e in phase["entries"]:
                if e.get("cold_ms") is None:
                    continue
                rows.append([e["server"], phase["suite"],
                             f"{e['cold_ms']:.1f}", f"{e['warm_ms']:.2f}",
                             f"{e.get('ratio', 0):.0f}x"])
        if rows:
            out += ["## Cold start", "",
                    "The first request after the cache is empty, against the same request warm. "
                    "Traffic here has a weekly shape — five busy days, then a trough — and the "
                    "page cache expires in an hour, so this is what the first user on Monday "
                    "gets. A suite that warms up before measuring never shows it.", "",
                    R.table(["server", "suite", "cold ms", "warm ms", ""], rows), ""]

    if results.get("soak"):
        out += ["## At the operating point", "",
                "A fixed arrival rate, held. These rates come from real traffic — this "
                "workload runs at a few requests a second with spikes into the tens — so "
                "what is being measured is latency and footprint where the server actually "
                "lives, not where it falls over.", "",
                "`rss peak` is the column to read under a spike: throughput headroom says "
                "nothing about memory, and a cache bounded by entry count rather than bytes "
                "grows with the *variety* of what is asked for, not the rate.", ""]
        for phase in results["soak"]:
            out += [f"### {phase['suite']} — {phase['rate']:g} req/s", "",
                    soak_rows(phase["entries"]), ""]

    if results.get("closed"):
        out += ["## Latency at fixed concurrency", ""]
        for phase in results["closed"]:
            out += [f"### {phase['suite']} — concurrency {phase['concurrency']}", "",
                    closed_rows(phase["entries"], results), ""]

    # Where the time went, at the highest concurrency each suite ran at --
    # the point where the server is working hardest and the shape is clearest.
    breakdowns = []
    if results.get("closed"):
        top = max((p["concurrency"] for p in results["closed"]), default=None)
        for phase in results["closed"]:
            if phase["concurrency"] != top:
                continue
            rows = phase_rows(phase["entries"])
            if rows:
                breakdowns += [f"### {phase['suite']} — concurrency {top}", "", rows, ""]
    if breakdowns:
        out += ["## Where the time went", "",
                "The server's own account of each request, from `Server-Timing`. "
                "`— accounted` is the phases added up and `— service p50` is what the "
                "client measured; the gap between them is the network, the accept, and "
                "anything outside the instrumented path. A large gap is worth chasing — "
                "it means time is going somewhere nothing is watching.", ""] + breakdowns

    if results.get("origin_totals"):
        out += ["## Origin traffic", "",
                "Range requests each server pulled from the origin during the timed windows.", ""]
        rows = [[k, v["requests"], round(v["bytes"] / 1e6, 1)]
                for k, v in sorted(results["origin_totals"].items())]
        out += [R.table(["server", "requests", "MB"], rows), ""]

    return "\n".join(out)


# ── Main ──────────────────────────────────────────────────────────────────────

def main() -> None:
    ap = argparse.ArgumentParser(description="sabre benchmarking suite")
    ap.add_argument("--sabre", default="http://127.0.0.1:8787")
    ap.add_argument("--titiler", default="http://127.0.0.1:8000")
    ap.add_argument("--origin", default="http://origin")
    ap.add_argument("--cog", default="dem.tif")
    ap.add_argument("--dataset", default=os.path.join(HERE, "data", "dem.tif"),
                    help="local path to the COG, fingerprinted into the results")
    ap.add_argument("--client", default=os.path.join(REPO, "target", "release", "bench-client"))
    ap.add_argument("--client-ssh", default=None, metavar="HOST",
                    help="run bench-client on this ssh host instead of locally, so the "
                         "generator stops competing with the servers for cores")
    ap.add_argument("--loopback-suites", default="info",
                    help="suites to keep on a local generator even when --client-ssh is set, "
                         "because they answer faster than the network between the boxes")
    ap.add_argument("--out", default=os.path.join(HERE, "out", "suite"))
    ap.add_argument("--origin-log", default=os.path.join(HERE, "out", "logs", "access.log"))
    ap.add_argument("--compose-file", default=os.path.join(HERE, "docker-compose.yml"))
    ap.add_argument("--servers", default="sabre",
                    help="which servers to measure. sabre alone by default: this suite is for "
                         "characterising sabre under load, not for comparing it. Whether the "
                         "two agree is bench/verify.py's job, and it runs on its own schedule. "
                         "Pass sabre,titiler to put titiler back in.")
    ap.add_argument("--suites", default="tiles,point,polygon,info,blocks,clip,imagery",
                    help="blocks/clip/imagery need bench/blocks and bench/data/scenes; "
                         "they are skipped with a note when either is absent")
    ap.add_argument("--zooms", default="6,8,10")
    ap.add_argument("--concurrency", default="1,8,32")
    ap.add_argument("--duration", type=float, default=10.0, help="seconds per fixed-concurrency phase")
    ap.add_argument("--warmup", type=float, default=3.0)
    ap.add_argument("--knee", action="store_true",
                    help="also find the saturation knee. Off by default: production here peaks "
                         "around 16 req/s against 100-680 sustained, so the knee is a cliff "
                         "nothing is driving towards, and probing for it is most of the runtime.")
    ap.add_argument("--rates", default="5,20",
                    help="open-loop rates to hold, in req/s. The operating point, not the limit.")
    ap.add_argument("--soak", type=float, default=30.0, help="seconds to hold each rate")
    ap.add_argument("--cold-start", action="store_true",
                    help="measure the first request after the caches are cold. A weekly traffic "
                         "trough expires everything, so this is what Monday morning costs.")
    ap.add_argument("--rss", default="",
                    help="what to sample memory from: pid:<n> or docker:<compose service>")
    ap.add_argument("--knee-probe", type=float, default=5.0)
    ap.add_argument("--knee-confirm", type=float, default=15.0)
    ap.add_argument("--targets", type=int, default=100, help="distinct URLs per suite")
    ap.add_argument("--polygon-px", type=int, default=512)
    ap.add_argument("--blocks-dir", default=os.path.join(HERE, "blocks"))
    ap.add_argument("--scenes-dir", default=os.path.join(HERE, "data", "scenes"))
    ap.add_argument("--farms", default="", help="comma-separated block set names; default is all of them")
    ap.add_argument("--imagery-asset", default="red",
                    help="which scene asset the imagery and blocks suites read")
    ap.add_argument("--imagery-zooms", default="13,15,17",
                    help="zooms for the imagery suite — where farm maps actually sit, "
                         "unlike the synthetic raster's 6/8/10")
    ap.add_argument("--colormap", default="viridis")
    ap.add_argument("--band", type=int, default=1)
    ap.add_argument("--seed", type=int, default=42)
    ap.add_argument("--wait", type=float, default=180)
    ap.add_argument("--verbose", action="store_true")
    ap.add_argument("--print-git", action="store_true",
                    help="print this checkout's provenance as JSON and exit. remote-bench.sh "
                         "runs this locally and passes the result to the box, which has no .git.")
    args = ap.parse_args()

    if args.print_git:
        meta = git_meta()
        if not meta.get("available"):
            sys.exit(meta.get("reason", "no git metadata available here"))
        print(json.dumps(meta, sort_keys=True))
        return

    os.makedirs(args.out, exist_ok=True)
    wanted = [s.strip() for s in args.servers.split(",") if s.strip()]
    servers = [s for s in (R.Sabre(args.sabre, f"{args.origin}/sabre/{args.cog}"),
                           R.Titiler(args.titiler, f"{args.origin}/titiler/{args.cog}"))
               if s.name in wanted]
    if not servers:
        sys.exit(f"no known servers in --servers {args.servers!r}")

    print("Waiting for servers …")
    for s in servers:
        # Exits with its own message if the server never answers.
        print(f"  {s.name:8} {s.base}  ready in {R.wait_healthy(s, args.wait):.1f}s")

    # Same extent and dataset shape as run.py, so the two reports describe the
    # same requests and their numbers can sit next to each other.
    extent = (10.0, 0.0, 12.0, 2.0)
    width = 4096
    pixel_deg = (extent[2] - extent[0]) / width
    style = R.Style(colormap=args.colormap, vmin=0.0, vmax=3000.0, band=args.band)

    rng = random.Random(args.seed)
    zooms = [int(z) for z in args.zooms.split(",") if z.strip()]
    suites = [s.strip() for s in args.suites.split(",") if s.strip()]
    concurrencies = [int(c) for c in args.concurrency.split(",") if c.strip()]
    rates = [float(r) for r in args.rates.split(",") if r.strip()]
    resources = Resources(args.rss, args.compose_file)
    if args.rss and not resources.available:
        print(f"  note: cannot read memory from {args.rss!r}; the run will have no footprint column")

    tiles = {z: R.sample(rng, R.tiles_at_zoom(extent, z), args.targets) for z in zooms}
    inset = pixel_deg
    points = [(rng.uniform(extent[0] + inset, extent[2] - inset),
               rng.uniform(extent[1] + inset, extent[3] - inset)) for _ in range(args.targets)]
    side = args.polygon_px * pixel_deg
    boxes = []
    for _ in range(max(1, args.targets // 2)):
        w = rng.uniform(extent[0], max(extent[0], extent[2] - side))
        s_ = rng.uniform(extent[1], max(extent[1], extent[3] - side))
        boxes.append((w, s_, min(w + side, extent[2]), min(s_ + side, extent[3])))

    # ── Real workloads ───────────────────────────────────────────────────────
    #
    # The suites above run on the synthetic DEM: random boxes scattered over a
    # 2-degree extent, at zooms where a tile spans hundreds of kilometres. That
    # is a control, not a workload. These run on real farm blocks over the
    # Sentinel-2 scene underneath them, which differs in the two ways that
    # decide how a tile server behaves -- the requests are small and they are
    # clustered, so a whole farm lands in a couple of COG tiles instead of
    # scattering across the raster.
    needs_real = {"blocks", "clip", "imagery"} & set(suites)
    farms = load_farms(args.blocks_dir, args.scenes_dir, args.farms) if needs_real else []
    if needs_real and not farms:
        print(f"  note: {', '.join(sorted(needs_real))} asked for but no block set has imagery; "
              f"skipping. Run bench/make_blocks.py then bench/fetch_scenes.py.")
        suites = [x for x in suites if x not in needs_real]

    # One field per request, cycled in the order the generator will send them.
    # Held per farm so the clip suite reuses the tile each block resolved to.
    fields = {
        f["name"]: [
            {"geometry": ft["geometry"], "tile": R.tile_for_geometry(ft["geometry"])}
            for ft in f["features"]
        ]
        for f in farms
    }
    imagery_zooms = [int(z) for z in args.imagery_zooms.split(",") if z.strip()]

    def farm_named(name: str) -> dict:
        return next(f for f in farms if f["name"] == name)

    def reqs_for(server, suite: str):
        if suite.startswith("tiles z="):
            z = int(suite.split("=")[1])
            return [server.tile(z, x, y, style) for (z, x, y) in tiles[z]]
        if suite == "point":
            return [server.point(lon, lat, style) for lon, lat in points]
        if suite == "polygon":
            return [server.polygon(b, style) for b in boxes]
        if suite == "info":
            return [server.info() for _ in range(min(args.targets, 20))]

        if suite.startswith("blocks "):
            farm = farm_named(suite.split(" ", 1)[1])
            url = scene_url(args.origin, server.name, farm["scene"], args.imagery_asset)
            return [server.zonal(f["geometry"], style, url) for f in fields[farm["name"]]]

        if suite.startswith("clip "):
            farm = farm_named(suite.split(" ", 1)[1])
            url = scene_url(args.origin, server.name, farm["scene"], args.imagery_asset)
            reqs = [server.clip(f["geometry"], *f["tile"], style, url=url)
                    for f in fields[farm["name"]]]
            # A server with no equivalent operation returns None throughout;
            # the phase records that as a skip rather than as a zero.
            return [r for r in reqs if r is not None]

        if suite.startswith("imagery z="):
            z = int(suite.split("=")[1])
            farm = farms[0]
            url = scene_url(args.origin, server.name, farm["scene"], args.imagery_asset)
            # Tiles over the farm, not over the whole 110 km scene: panning
            # around one property is the request a farm map makes, and it is
            # also what keeps the reads clustered.
            at_z = R.tiles_at_zoom(tuple(farm["shape"]["bbox"]), z)
            if not at_z:
                return []
            return [server.tile(zz, x, y, style, url) for (zz, x, y) in R.sample(rng, at_z, args.targets)]

        raise ValueError(suite)

    phases = []
    if "tiles" in suites:
        phases += [f"tiles z={z}" for z in zooms]
    for extra in ("point", "polygon", "info"):
        if extra in suites:
            phases.append(extra)
    if "blocks" in suites:
        phases += [f"blocks {f['name']}" for f in farms]
    if "clip" in suites:
        phases += [f"clip {f['name']}" for f in farms]
    if "imagery" in suites and farms:
        phases += [f"imagery z={z}" for z in imagery_zooms]

    remote = Client(args.client, quiet=not args.verbose, ssh=args.client_ssh)
    remote.check()
    # Suites too fast to measure across the network keep a local generator even
    # in the split setup. Sharing cores costs them throughput; the network would
    # cost them the measurement itself.
    local = Client(os.path.join(REPO, "target", "release", "bench-client"),
                   quiet=not args.verbose) if args.client_ssh else remote
    loopback = {x.strip() for x in args.loopback_suites.split(",") if x.strip()}
    if args.client_ssh:
        local_ok = os.path.exists(local.binary)
        if not local_ok and loopback:
            print(f"  note: no local bench-client at {local.binary}; "
                  f"{','.join(sorted(loopback))} will run over the network too")
            loopback = set()

    def client_for(suite: str) -> Client:
        return local if suite.split()[0] in loopback or suite in loopback else remote

    origin_log = R.OriginLog(args.origin_log)
    compose = R.Compose(args.compose_file)

    results = {
        "kind": "sabre-bench-suite",
        "version": 1,
        "started": time.strftime("%Y-%m-%dT%H:%M:%S"),
        "args": vars(args),
        "git": git_meta(),
        "host": host_meta(),
        "dataset": dataset_meta(args.dataset),
        "farms": [
            {"name": f["name"], "shape": f["shape"],
             "scene": {k: v for k, v in f["scene"].items() if k != "assets"},
             "assets": {k: a["file"] for k, a in (f["scene"].get("assets") or {}).items()}}
            for f in farms
        ],
        "servers": {s.name: {"base": s.base, "source": s.source} for s in servers},
        "topology": {
            "generator": "split" if args.client_ssh else "same-box",
            "generator_host": args.client_ssh,
            "loopback_suites": sorted(loopback),
        },
        "floor": {},
        "closed": [],
        "soak": [],
        "cold": [],
        "knee": [],
        "origin_totals": {},
    }
    if results["git"].get("dirty"):
        print(f"  note: working tree has {results['git']['dirty_files']} modified file(s); "
              f"this result is not attributable to {results['git'].get('short')}")

    # ── Floor ────────────────────────────────────────────────────────────────
    print("\nRound-trip floor (GET /health, concurrency 1)")
    for s in servers:
        f = measure_floor(remote, s, duration=2.0)
        results["floor"][s.name] = f
        if f:
            print(f"  {s.name:8} p50 {f['p50_ms']:.3f}ms   p99 {f['p99_ms']:.3f}ms"
                  + ("   <- includes the hop to the generator" if args.client_ssh else ""))

    pending_origin = []

    # ── Fixed concurrency ────────────────────────────────────────────────────
    for suite in phases:
        for c in concurrencies:
            entries = []
            print(f"\n{suite} — concurrency {c}")
            for s in servers:
                reqs = reqs_for(s, suite)
                if not reqs:
                    # No equivalent operation on this server, or nothing to ask
                    # for. Recorded as a skip: a missing row is easier to read
                    # correctly than a row of zeroes.
                    print(f"  {s.name:8} skipped — no comparable request")
                    entries.append({"server": s.name, "summary": None,
                                    "skipped": "no comparable request on this server"})
                    continue
                plan = plan_of(suite, s, reqs, {"closed": {"concurrency": c}},
                               duration=args.duration, warmup=args.warmup)
                summary = client_for(suite).run(plan)
                entry = {"server": s.name, "summary": summary, "generator": client_for(suite).where}
                if summary:
                    print(f"  {s.name:8} {summary['achieved_rps']:8.1f} req/s   "
                          f"p50 {summary['service_ms']['p50']:7.2f}ms   "
                          f"p99 {summary['service_ms']['p99']:8.2f}ms   "
                          f"{summary['errors']} err")
                    pending_origin.append((entry, s.log_prefix, summary))
                entries.append(entry)
            results["closed"].append({"suite": suite, "concurrency": c, "entries": entries})

    # ── Cold start ───────────────────────────────────────────────────────────
    #
    # Traffic here has a weekly shape: five busy days, then a trough at about a
    # fifth of the volume. The page cache TTL is an hour, so by Monday morning
    # nothing is warm, and the first request of the week pays the full cost of
    # reaching the origin. A suite that warms up and then measures steady state
    # never sees that, which is how it stays a surprise.
    if args.cold_start:
        print("\nCold start — first request after the cache is emptied")
        for suite in phases:
            entries = []
            for s_ in servers:
                reqs = reqs_for(s_, suite)
                if not reqs:
                    continue
                compose.restart(s_.service)
                R.wait_healthy(s_, args.wait)
                plan = plan_of(f"{suite} cold", s_, reqs[:1],
                               {"closed": {"concurrency": 1}},
                               duration=None, warmup=0.0)
                plan["requests"] = 1
                cold = client_for(suite).run(plan)
                # Then the same request again, now warm, for the ratio.
                warm = client_for(suite).run(dict(plan, requests=5))
                entry = {"server": s_.name,
                         "cold_ms": cold["service_ms"]["p50"] if cold else None,
                         "warm_ms": warm["service_ms"]["p50"] if warm else None}
                if entry["cold_ms"] and entry["warm_ms"]:
                    ratio = entry["cold_ms"] / max(entry["warm_ms"], 1e-9)
                    entry["ratio"] = ratio
                    print(f"  {s_.name:8} {suite:32} "
                          f"cold {entry['cold_ms']:8.1f}ms   warm {entry['warm_ms']:7.2f}ms   "
                          f"{ratio:5.0f}x")
                entries.append(entry)
            results["cold"].append({"suite": suite, "entries": entries})

    # ── Soak at the operating point ──────────────────────────────────────────
    #
    # A fixed arrival rate held long enough to see the footprint settle, rather
    # than a ramp towards saturation. The rates come from real traffic: this
    # workload runs at a few req/s with spikes into the tens, so what matters
    # is latency and memory there, not where the cliff is.
    if rates:
        for suite in phases:
            for rate in rates:
                entries = []
                print(f"\n{suite} — holding {rate} req/s for {args.soak:.0f}s")
                for s_ in servers:
                    reqs = reqs_for(s_, suite)
                    if not reqs:
                        entries.append({"server": s_.name, "summary": None,
                                        "skipped": "no comparable request on this server"})
                        continue
                    plan = plan_of(suite, s_, reqs, {"open": {"rate": rate}},
                                   duration=args.soak, warmup=args.warmup)
                    resources.start()
                    summary = client_for(suite).run(plan)
                    rss = resources.stop()
                    entry = {"server": s_.name, "summary": summary, "rss": rss,
                             "generator": client_for(suite).where}
                    if summary:
                        served = summary["ok"]
                        kb = (summary["bytes"] / served / 1024) if served else 0.0
                        print(f"  {s_.name:8} {summary['achieved_rps']:6.1f} req/s   "
                              f"p50 {summary['service_ms']['p50']:6.2f}ms   "
                              f"p99 {summary['service_ms']['p99']:7.2f}ms   "
                              f"{kb:6.1f} KB/req"
                              + (f"   rss {rss['rss_mb_p50']:.0f}→{rss['rss_mb_peak']:.0f} MB"
                                 if rss else ""))
                        pending_origin.append((entry, s_.log_prefix, summary))
                    entries.append(entry)
                results["soak"].append({"suite": suite, "rate": rate, "entries": entries})

    # ── Sustained throughput ─────────────────────────────────────────────────
    if args.knee:
        for suite in phases:
            if suite == "info":
                # /info answers in a few hundred microseconds, below the
                # generator's scheduling resolution. An open-loop number here
                # would describe the timer, not the server.
                print("\ninfo — skipping knee (below the generator's timer resolution)")
                continue
            entries = []
            print(f"\n{suite} — sustained throughput")
            for s in servers:
                reqs = reqs_for(s, suite)
                if not reqs:
                    print(f"  {s.name:8} skipped — no comparable request")
                    entries.append({"server": s.name, "knee": {},
                                    "skipped": "no comparable request on this server"})
                    continue
                seed = 100.0
                for ph in results["closed"]:
                    if ph["suite"] == suite and ph["concurrency"] == max(concurrencies):
                        for e in ph["entries"]:
                            if e["server"] == s.name and e["summary"]:
                                seed = max(e["summary"]["achieved_rps"], 10.0)
                knee = find_knee(client_for(suite), plan_of(suite, s, reqs, {"open": {"rate": seed}},
                                                 duration=args.knee_probe, warmup=args.warmup),
                                 seed_rps=seed, probe_s=args.knee_probe, confirm_s=args.knee_confirm)
                k = knee.get("knee_rps")
                print(f"  {s.name:8} sustained {k:.0f} req/s" if k else f"  {s.name:8} no knee found")
                if knee.get("note"):
                    print(f"           {knee['note']}")
                entries.append({"server": s.name, "knee": knee})
                if knee.get("confirm_summary"):
                    pending_origin.append(({"server": s.name}, s.log_prefix, knee["confirm_summary"]))
            results["knee"].append({"suite": suite, "entries": entries})

    # ── Origin accounting ────────────────────────────────────────────────────
    # The origin writes its log line after the server under test has already
    # answered, so lines are attributed once the whole run is over and the log
    # has gone quiet, never phase by phase as they run.
    if origin_log.available and pending_origin:
        origin_log.settle()
        totals = {}
        for entry, path, summary in pending_origin:
            window = summary.get("window")
            if not window:
                continue
            got = origin_log.between(window, path)
            entry["origin"] = got
            t = totals.setdefault(entry.get("server", "?"), {"requests": 0, "bytes": 0})
            t["requests"] += got["requests"]
            t["bytes"] += got["bytes"]
        results["origin_totals"] = totals

    results["finished"] = time.strftime("%Y-%m-%dT%H:%M:%S")
    for s in servers:
        mb = compose.memory_mb(s.service) if compose.ok else None
        results["servers"][s.name]["memory_mb_end"] = mb

    json_path = os.path.join(args.out, "suite.json")
    md_path = os.path.join(args.out, "suite.md")
    with open(json_path, "w") as f:
        json.dump(results, f, indent=2)
    report = build_report(results)
    with open(md_path, "w") as f:
        f.write(report + "\n")

    print("\n" + report)
    print(f"\nWrote {json_path} and {md_path}")


if __name__ == "__main__":
    main()
